/*
	Problem 2

	Each new term in the Fibonacci sequence is generated by adding the previous
	two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed
	four million, find the sum of the even-valued terms.
*/

#include <iostream>
#include "../timer.h"

#define LIMIT 4000000

int main()
{
	ProgramTimer timer;

	int f1 = 1, f2 = 2, f3 = 3;
	int sum = 2;

	while (f3 < LIMIT) {
		f1 = f2;
		f2 = f3;
		f3 = f1 + f2;
		if (f3 % 2 == 0)
			sum += f3;
	}

	std::cout << sum << '\n';

	timer.print_time();
	return 0;
}

/*
	Solution:	4613732
	Avg time:	2.9138e-05s
*/
